repos:
-   repo: local
    hooks:
      - id: format-sql
        name: format sql files
        entry: bash ./pre-commit/format.sh
        language: system
        pass_filenames: false
-   repo: local
    hooks:
      - id: tsqllint
        name: run tsqllint
        entry: tsqllint
        language: system
        args: [".", "--config", ".tsqllint"]
        files: ".*\\.sql$"
-   repo: local
    hooks:
      - id: build-db
        name: build the db model
        entry: dotnet build hows-the-weather/hows-the-weather.csproj
        language: system
        pass_filenames: false