name: cd-deploy-db

on:
  push:
    branches:
    - main

jobs:
    build-db:
        runs-on: ubuntu-22.04
        environment: main
        steps:
            - 
                uses: actions/checkout@v4
    
            -
                name: Install SqlProj
                run: |
                    dotnet new --install MSBuild.Sdk.SqlProj.Templates
    
            -
                name: Create sqlproj
                run: |
                    dotnet new sqlproj -s SqlAzure --name hows-the-weather --force
    
            -
                name: Build db model
                run: |
                    dotnet build hows-the-weather/hows-the-weather.csproj
            -
                name: Add MSFT key
                run: |
                    curl https://packages.microsoft.com/keys/microsoft.asc | sudo tee /etc/apt/trusted.gpg.d/microsoft.asc

            -
                name: Add MSFT repo
                run: |
                    curl https://packages.microsoft.com/config/ubuntu/22.04/prod.list | sudo tee /etc/apt/sources.list.d/mssql-release.list

            -
                name: apt update
                run: |
                    sudo apt update

            -
                name: install mssql
                run: |
                    ACCEPT_EULA=Y sudo apt-get install mssql-tools18 unixodbc-dev -y 

            -
                name: Add sqlcmd to path
                run: |
                    export PATH="$PATH:/opt/mssql-tools18/bin"

            -
                name: install sqlpackage
                run: |
                    dotnet tool install --global microsoft.sqlpackage

            -
                name: add dotnet tooling to path
                run: |
                    export PATH="${PATH}:/root/.dotnet/tools"

            -
                name: deploy database
                run: |
                    sqlpackage /Action:Publish \
                    /SourceFile:hows-the-weather/bin/Debug/netstandard2.0/hows-the-weather.dacpac \
                    /TargetConnectionString:"Data Source=${{ secrets.DB_DEPLOY_HOST }}; Initial Catalog=${{ secrets.DB_DEPLOY_DATABASE }}; UID=${{ secrets.DB_DEPLOY_USER }}; PWD=${{ secrets.DB_DEPLOY_PASS }}"

            - 
                name: post deploy user creation
                run: |
                    sqlcmd \
                    -S ${{ secrets.DB_DEPLOY_HOST }} \
                    -d ${{ secrets.DB_DEPLOY_DATABASE }} \
                    -U ${{ secrets.DB_DEPLOY_USER }} \
                    -P ${{ secrets.DB_DEPLOY_PASS }} \
                    -i hows-the-weather/PostDeploy/user_creation.sql \
                    -G

            - 
                name: post deploy user permissions
                run: |
                    sqlcmd \
                    -S ${{ secrets.DB_DEPLOY_HOST }} \
                    -d ${{ secrets.DB_DEPLOY_DATABASE }} \
                    -U ${{ secrets.DB_DEPLOY_USER }} \
                    -P ${{ secrets.DB_DEPLOY_PASS }} \
                    -i hows-the-weather/PostDeploy/user_permissions.sql \
                    -G
