name: cd-deploy-db

on:
  push:
    branches:
    - main

jobs:
  tsqllint:
    runs-on: ubuntu-latest
    steps:
        - 
            uses: actions/checkout@v4

        -
            name: Install SqlProj
            run: |
                dotnet new --install MSBuild.Sdk.SqlProj.Templates

        -
            name: Create sqlproj
            run: |
                dotnet new sqlproj -s SqlAzure --name dbmodel

        -
            name: Build dbmodel
            run: |
                dotnet build dbmodel/dbmodel.sqlproj

        
        
        
