name: ci-tsqllint

on:
  pull_request:
    branches:
    - main

jobs:
  tsqllint:
    runs-on: ubuntu-22.04
    steps:
        - 
            uses: actions/checkout@v4

        -
            name: Install Dotnet
            run: |
                sudo apt-get install -y dotnet-sdk-9.0

        -
            name: Install tsqllint
            run: |
                dotnet tool install --global TSQLLint

        -
            name: run tsqllint
            run: |
                tsqllint . --config .tsqllint


        
        
        
