name: data-house-ci

on:
  pull_request:
    branches:
    - main
    paths:
      - "dbmodel/**"
      - "deploy/**"
      - ".github/workflows/**"

jobs:
  build-steps:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/gregkinne/dbdeploy            
          # generate Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha            
      -
        name: Build Dockerfile
        uses: docker/build-push-action@v5
        with:
          file: deploy/dbdeploy.Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true
  
  dev-deployment:
    runs-on: ubuntu-latest
    needs: build-steps
    container:
      image: ghcr.io/gregkinne/dbdeploy
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4

      - 
        name: test
        id: test
        run: docker run dbdeploy echo "test"
          
