name: data-house-ci

on:
  pull_request:
    branches:
    - main
    paths:
      - "dbmodel/**"
      - "deploy/**"
      - ".github/workflows/**"

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      -
        name: Build Dockerfile
        uses: docker/build-push-action@v5
        with:
          file: deploy/dbdeploy.Dockerfile
          tags: |
            ghcr.io/gregkinne/dbdeploy:latest 
          push: true
  #docker-run-dotnet-build:
    #runs-on: docker
    #steps:
      #-
        #name: testing
        #run: docker run dotnet build ./dbmodel/dbmodel.csproj
          
