name: data-house-ci

on:
  pull_request:
    branches:
    - main
    paths:
      - "dbmodel/**"
      - "deploy/**"
      - ".github/workflows/**"

jobs:
  local-docker-build:
    runs-on: ubuntu-latest
    steps:
      -
        name: build the dbdeploy dockerfile
        id: build-dockerfile
        run: docker build --file deploy/Dockerfile --tag dbdeploy .

      -
        name: generate the sqlproj file
        run: dotnet new sqlproj -s Sql150 --name dbmodel
        id: generate-sqlproj

      -
        name: build the database model
        run: dotnet build ./dbmodel/dbmodel.csproj  
        id: build-dbmodel

      -
        name: run the TSQL linter
        run: tsqllint --print-config
        id: run-linter
